---
enabled: true
priority: 100
tools:
    - name: opencode
      enabled: true
      install-priority: 100
      install:
        macos: |
            #
        ubuntu: |
            #
      bootstrap:
        - priority: 100
          default: |
            export PATH="$HOME/.opencode/bin:$PATH"

    - name: kiro-cli
      enabled: true
      bootstrap:
        - priority: 70
          macos: |
            builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"
        - priority: 110
          macos: |
            builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
